apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-secret
spec:
  secretStoreRef:
    name: aws-secret-store
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: postgress-secrets
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: postgress-secrets
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: postgress-secrets
        property: DB_USER