apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appname }}-deployment
  labels:
    app: {{ .Values.frontend.appname }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.appname }}
      {{- include "library.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appname }} 
        {{- include "library.labels" . | nindent 8 }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        volumeMounts:
        - name: frontend-volume
          mountPath: /usr/share/nginx/html
        resources: {}
      volumes:
      - name: {{ .Values.frontend.appname }}-volume
        hostPath:
          path: ./frontend
          type: Directory
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appname }}-service
spec:
  selector:
    app: {{ .Values.frontend.appname }}
    {{- include "library.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP