name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Starting CI Process"

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: run docker compose
        run: docker compose up -d

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '15'

      - name: tests by using curl
        run: curl http://localhost:80

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 992382853618.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Get the latest commit SHA
        id: git-info
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image from frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            992382853618.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/eitan/project:frontend-${{ env.sha }}

      - name: Build and push Docker image from backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            992382853618.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/eitan/project:backend-${{ env.sha }}

      # - name: Update image tags in GitOps repository
      #   run: |
      #     git clone https://github.com/your-org/gitops-repo.git
      #     cd gitops-repo
      #     sed -i "s|image: .*frontend.*|image: 992382853618.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/eitan/project:frontend-${{ env.sha }}|" path/to/frontend/deployment.yaml
      #     sed -i "s|image: .*backend.*|image: 992382853618.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/eitan/project:backend-${{ env.sha }}|" path/to/backend/deployment.yaml
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"
      #     git add .
      #     git commit -m "Update image tags to commit ${{ env.sha }}"
      #     git push
