name: CI

on:
  push:
    branches:
      - main
      - '!versioning'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Starting CI Process"


      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'


      - name: run docker compose 
        run: docker compose up -d


      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '15'

      - name: tests by using curl
        run: curl http://localhost:80

      - name: Fetch versioning branch
        run: git fetch origin versioning

      - name: Checkout versioning branch
        run: git checkout versioning -- .env || echo "No existing .env file"

      - name: Generate date-time and next version
        id: versioning
        run: |
          if [ -f ".env" ]; then
            source .env
          else
            VERSION_COUNTER=0
          fi

          VERSION_COUNTER=$((VERSION_COUNTER + 1))

          # Generate date-time string
          DATE=$(date +%Y%m%d%H%M)

          # Combine date-time and counter
          VERSION="v$DATE-$VERSION_COUNTER"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "VERSION_COUNTER=$VERSION_COUNTER" > .env

      - name: Commit updated .env file to versioning branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -B versioning
          git pull origin versioning --rebase || echo "No remote versioning branch to pull from"
          git add .env
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update version counter to ${{ env.VERSION }}"
            git push origin versioning
          fi

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382853618.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image from frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project:frontend-${{ env.VERSION }}

      - name: Build and push Docker image from backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: |
            992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project:backend-${{ env.VERSION }}
